///
/// @Generated by Mockolo
///

import Foundation
import RealmSwift

@testable import SimpleTodoListPackage

class TodoRepositoryProtocolMock: TodoRepositoryProtocol {
    init() { }

    private(set) var createCallCount = 0
    var createHandler: ((Todo) -> Void)?
    func create(todo: Todo) {
        createCallCount += 1
        if let createHandler = createHandler {
            createHandler(todo)
        }

    }

    private(set) var getByIdCallCount = 0
    var getByIdHandler: ((String) -> (Todo))?
    func getById(id: String) -> Todo {
        getByIdCallCount += 1
        if let getByIdHandler = getByIdHandler {
            return getByIdHandler(id)
        }
        fatalError("getByIdHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var getAllCallCount = 0
    var getAllHandler: (() -> ([Todo]))?
    func getAll() -> [Todo] {
        getAllCallCount += 1
        if let getAllHandler = getAllHandler {
            return getAllHandler()
        }
        return [Todo]()
    }

    private(set) var updateCallCount = 0
    var updateHandler: ((Todo) -> Void)?
    func update(todo: Todo) {
        updateCallCount += 1
        if let updateHandler = updateHandler {
            updateHandler(todo)
        }

    }

    private(set) var deleteCallCount = 0
    var deleteHandler: ((Todo) -> Void)?
    func delete(todo: Todo) {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            deleteHandler(todo)
        }

    }
}
